### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Axelwickm** [Axelwickm/DenseSense#1]
- [x] Make Python 3
- [ ]  Python 2 version
- [x] Upgrade to detectron2
- [x] Integrate with new version of DensePose
- [x] Make more APIy
- [x] Don't use websockets
- [x] Provide webcam example
- [ ] More comments
- [x] Write requirements.txt
- [x] General cleanup
- [x] Finish sanitizer
- [ ] Finish gesture recognition
- [x] Split everything in Algorithms into files
- [ ] Documentation
- [ ] Configuration file
